### ISSUE TITLE
Multiple elements not working in Firefox when privacy.resistFingerprinting = true

### ISSUE THREAD

**Issue by MooToYouToo** [airjp73/kifu-io#1]
Great app, been looking for an eidogo replacement for ages, but it's not working well with Firefox 81.0.1 (64-bit) on Windows 10. (edit: when privacy.resistFingerprinting = true in about:config)

Issues:

- Upload elements are missing 
![image](https://user-images.githubusercontent.com/15002248/95128807-7ca30e80-0749-11eb-88d9-814b9ec30dfc.png)
- Hamburger menu button has no effect when window size hides the menu
- 'Comments', 'Info', Change Color and the dots menu buttons in the picture have no effect when clicked. (Save to server button does work)
![image](https://user-images.githubusercontent.com/15002248/95129010-d7d50100-0749-11eb-88c0-96b235acbe8d.png)

**Comment by airjp73** [comment]
Hi! I haven't checked this repo in a while -- sorry I didn't notice the issue. Is this still broken for you?

**Comment by airjp73** [comment]
Going to close as an old issue. Please feel free to reopen if this is still an issue. 😊
