### ISSUE TITLE
Procedure to install on my webserver

### ISSUE THREAD

**Issue by 3kakakhel** [airjp73/kifu-io#4]
Thank you for putting together all this work to make such a project.
I am new to using Typescript. From what I understand, to get this project
up and running on my server, I need to do the following.

1.  Download the zip file;  Extract the zip file.
2.  Install Node,js;  Install Typescript.
3.  Run `tsc` in the same folder as the `tsconfig.json` file.
4.  There will be a fully populated `public` folder.
5.  Place all the contents of that `public` folder into my webserver.

While running `tsc`, I got [717 errors](https://pastebin.com/mBfN1kPa).
Clearly I missed something important. 
I would appreciate guidance on what do from here.

**Comment by airjp73** [comment]
Hi! This project isn't really set up to be installed on a webserver like that. If you're interested in using this, you can find it at https://kifu.io/.

**Comment by 3kakakhel** [comment]
Aaron,

Thanks for getting back to me on this question. Thanks for building this
project. 👍


Ali
